Upward traversal optimization
morpho-labs/data-structures pull request #47
Opened 2022-07-06 08:58 UTC by QGarchery

Fixes 
- #39 

Before changes (only significant function is `updateHeap`):
![before-swap-same](https://user-images.githubusercontent.com/22668539/177512001-f4e2cb35-b2cc-4ca1-8710-4a8ba85a70cc.png)

After changes:
![after-shiftup-break](https://user-images.githubusercontent.com/22668539/177512057-42859fdd-b9e9-46a7-9341-d69b191df7a3.png)

2022-07-06 12:12 UTC, MerlinEgalite requested changes

2022-07-06 12:25 UTC, QGarchery commented
![after-merlin](https://user-images.githubusercontent.com/22668539/177549704-0d9731e6-76e4-4d75-a212-4fe36016d291.png)

2022-07-12 08:17 UTC, MerlinEgalite approved these changes
LGTM

2022-07-12 09:25 UTC, QGarchery commented
Changing tests to only the one with 10000 possible values:
![before](https://user-images.githubusercontent.com/22668539/178457760-77c27e32-fef6-4e1c-a702-929bcd1647ab.png)

after changes of this PR:
![after-shiftup](https://user-images.githubusercontent.com/22668539/178457934-c4df8656-3b85-4768-9463-9f118880310f.png)

2022-07-12 11:36 UTC, MathisGD approved these changes

2022-07-12 12:59 UTC, merged