Changes from Omniscia's full review
morpho-labs/data-structures pull request #52
Opened 2022-07-08 18:30 UTC by QGarchery

This PR sums up the changes made in response to the Omniscia's report.

It fixes:
- #35 (see also #49)
- #40 (see also #44) 
- #41 (see also #44)
- #42 (see also #44)
- #32 (see  also #45)
- #34 (see also #45)
- #37 (see also #45)
- #33 (see also #46)
- #39 (see also #47)

We acknowlege the following issues without addressing them. See the comment section in the respective issues for reasons why.
- #36 
- #43
- #38 (see also #48)

2022-07-09 09:42 UTC, MerlinEgalite commented
I can't see https://github.com/morpho-labs/data-structures/issues/40 fixed in https://github.com/morpho-labs/data-structures/pull/44

2022-07-09 09:53 UTC, MerlinEgalite requested changes
I can't see #40 and  #42 fixed in #44 ...

The still pending PRs seems not to bring gas improvements at all, I'm for closing it.
A bit surprised for the #39 though.

I agree with the acknowledgment for the #36 but left a comment for the #43

2022-07-09 13:33 UTC, QGarchery commented
> I can't see #40 and #42 fixed in #44 ...

What do you mean ? Commits in this PR are even referencing the issues they fix.

> The still pending PRs seems not to bring gas improvements at all, I'm for closing it. A bit surprised for the #39 though.

#33 is surprising too, I don't really know how to make sense of the results

> I agree with the acknowledgment for the #36 but left a comment for the #43

Answered back

2022-07-12 14:03 UTC, MathisGD approved these changes

2022-07-26 14:55 UTC, MerlinEgalite approved these changes

2022-07-26 14:55 UTC, merged